apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mkdocs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Westerley/gitops-argocd.git
    targetRevision: HEAD
    path: k8s/web
  destination:
    server: https://kubernetes.default.svc
    namespace: web
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true